version: 0.4.0
publish_to: none
name: realtimekit_ui
homepage: https://docs.realtime.cloudflare.com/
description: Cloudflare's RealtimeKit UI SDK to integrate video-audio to your app

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  get_it: ^9.2.1
  dyte_icons: 0.0.3
  file_picker: ^10.3.7
  flutter_riverpod: ^2.6.1
  realtimekit_core:
    git:
      ref: fluency/0.1.6/v7
      url: https://github.com/Nadii7/updated_realtimekit_core.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  melos: ^7.0.0
  flutter_lints: ^6.0.0

melos:
  useRootAsPackage: true

flutter:
  assets:
    - pubspec.yaml
    - assets/images/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
