version: 0.1.3
name: realtimekit_ui
homepage: https://docs.realtime.cloudflare.com/
description: Cloudflare's RealtimeKit UI SDK to integrate video-audio to your app

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  get_it: ^9.1.0
  dyte_icons: 0.0.3
  file_picker: ^10.3.7
  flutter_riverpod: ^2.6.1
  realtimekit_core: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  assets:
    - pubspec.yaml
    - assets/images/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
